language: node_js
node_js:
- '8'
sudo: false
branches:
  only:
  - master

os:
- linux

install:
- npm install
- npm run build

script:
- npm test --silent

notifications:
  slack:
    rooms:
      secure: iyIei0lVjumjNzqpsvgxkJZ04NugAvLLO6BdKQTaR+dwZxY/32gVMrtgex9TkS/V8BVOsovmQ/rNBTlphwE35L8kgMfnXEmCBYBz/0gxl/40GfHXrstMk5ZajwF9z+Cx1quoLP52eS2hECxvupSBUDdY69WcksF0netphvTzdGfx2CUbU0065+nSclraNaX6+h2VgE2JbTV4BjRawkGGsv/AgtzHNUFPZDdcDs7WgTa16WHjhwuyJiiQgmTmrazpepM8rnl0CUGgK6SaZN4NeZ6bbpf+63VVaobWVRIbTTfjwVmy7BBFaweo3DDSi3KA9hkjYkTBK4e4te/tQAD5xnyLab9GdO1GYH2GZol+9nHRYqKJp8aQ1uF9YET3MX1rrk3lW+DBLJAmbA3Tayr/eKWOh/RKxutsdf3J1ZV/JsRzwF0p1oPZBG1ueleWsEMpPqj0x3RRdbPdEohIONOJlVvWzYqmjrLTxl3VDh4kzQ1CVIqdc8prMzaKQuPGhSNsl9r6DKSYpqVJese72+ugcvS+S/wTB2QZhDMacah9xpFB2H+xapPWIavTjB/uR+/L7eOITzx9qN6CEkRTCxSz/Z4TB/wtCcjAO0WisHm6/5UwfNCdT/rUMchaCFHUnAE/cLnGncD9VqmIm5DGFbdZRI0aIo/M1kxYQhFJjfxnXEU=
      on_success: change
      on_failure: always