language: node_js
node_js:
- '8'
sudo: false
branches:
  only:
  - master
os:
- linux
install:
- yarn install
- yarn build
script:
- yarn test --silent
deploy:
  - provider: npm
    email: dev@xcomponent.com
    skip_cleanup: true
    api_key:
      secure: dajqLCZzFOAf3QZ2ZLF5ontjaduVzFJN2SjP0SK+aGiIHq7G+kWg1shj6stAzh17xUMl7K1L8xn16zKMT3zM9KTt30KpByoUJwVKEuvHdEaY5y3n8PtRx9YUoNotOscu1p1gx4raEfJY8gtfeyA0RS/n1oQPE3YPW9J/Vx9UOJkXdynEECmP7Onzsz1/GS4SfZCS/gt58dOp9hcIpOiSqs9H5fh8R0SvMHa1cfh6JAYt46pJZZClXvrpzMeZ/Hg2p4dWmoVREe5E3MtRw+JQfS5kFbi9JYH8NTNiAwOPiaknUlidXLaLvLzlOQOy0f8u5R8m9IZApRxDLcHTGMVYsPsxscL0fEwT8G2/r6EZqVQDtDxAoZZQg7+/nuvejSVtcnU8P6lU+T44ljGn6dkHZcrnNOY9co8Lk2wYJd6pI60DgMICDzMk937s7eSmOADM1RMjQ59D8EfNDj4+Xd8fFy4hbTeNZMttsCQ1ViqD4cKWsJ257zoimllSNBVnTg3tgmZLJzlyYCAZ6dAw/+7kwgT40qUhjmwkFyWHyOiAyDGQu9faL4U+6JprtZZuuUlOb7wRaRFSGorsSIhX1hdc1LRClWsV/IXV7ppvg75CWZSF1QA/SGZYn/LTYZ+zyawUFcf+yA53FI5dX9hSoYv4FPLrDMW4jOQaXOh3q6XbMj0=
    on:
      branch: master
      condition: "`./checkTag.sh` = RELEASE"
  - provider: npm
    email: dev@xcomponent.com
    skip_cleanup: true
    tag: next
    api_key:
      secure: dajqLCZzFOAf3QZ2ZLF5ontjaduVzFJN2SjP0SK+aGiIHq7G+kWg1shj6stAzh17xUMl7K1L8xn16zKMT3zM9KTt30KpByoUJwVKEuvHdEaY5y3n8PtRx9YUoNotOscu1p1gx4raEfJY8gtfeyA0RS/n1oQPE3YPW9J/Vx9UOJkXdynEECmP7Onzsz1/GS4SfZCS/gt58dOp9hcIpOiSqs9H5fh8R0SvMHa1cfh6JAYt46pJZZClXvrpzMeZ/Hg2p4dWmoVREe5E3MtRw+JQfS5kFbi9JYH8NTNiAwOPiaknUlidXLaLvLzlOQOy0f8u5R8m9IZApRxDLcHTGMVYsPsxscL0fEwT8G2/r6EZqVQDtDxAoZZQg7+/nuvejSVtcnU8P6lU+T44ljGn6dkHZcrnNOY9co8Lk2wYJd6pI60DgMICDzMk937s7eSmOADM1RMjQ59D8EfNDj4+Xd8fFy4hbTeNZMttsCQ1ViqD4cKWsJ257zoimllSNBVnTg3tgmZLJzlyYCAZ6dAw/+7kwgT40qUhjmwkFyWHyOiAyDGQu9faL4U+6JprtZZuuUlOb7wRaRFSGorsSIhX1hdc1LRClWsV/IXV7ppvg75CWZSF1QA/SGZYn/LTYZ+zyawUFcf+yA53FI5dX9hSoYv4FPLrDMW4jOQaXOh3q6XbMj0=
    on:
      branch: master
      condition: "`./checkTag.sh` = BETA"
notifications:
  slack:
    secure: hKTMOBgJ0iX6UKEPFPgoch1Z9UQ4JZZnJZSu7BCIyncvrOaUcotpfhYl94gtbWRRjvOqzxF9tGoTOQzTKR78BsotvavjGU3eV6+3jIMWu8Ld4WMInoo7hfNbzJ5RyPEnLlh4+lK5Gs4PjRElRtglo3I2k0dU7bfcZE1EgSANW1+qbCmuZneDnpTsQYq0KJE7Ql1LL4vd8nj1rQa2cy0E3Vi3Tz38wrmQDpMMlcMfzMX4BNlR+Ru7hcpp7py6n6Sg9TxXdN5nEPATkrc1fFNMBtdHuNY06g2BhzHdZdcz9TWOmuQhi5A2/4rjpbT+w4owSw3OBj0C0moG7v02FtAz2P021T9I+rL6XW9maw8jRXaSAO64/BuZ2MuDRqftQuv7bBIR+MN2eI5e9gNzyAR7QkYitIumHocGQdK6Fv6ztKcLKq19ErttNJ+kb2oNu8h7VOXahm7ZX9g8bkaMUJ18Vl03lwvJACYBXDh/zBpqp96GUSZPl1sa3JVjA1ehGIjdlUuV7Q6GKZnmEv537KhnONpaRvERi/MbuhJN0YrFiLbw7hiTO+wsNk4h6o6rALX79MV/dDk1SQOCZ0OwQtRyXGlrzCkAPzDHIgBbtGDjGnlOu9zpzaiBN7H6BO4ZfGyZJaa+CV5ljpRgHHiVC0zohz+x1SzeM+0lkh61Kb69BrM=
    on_success: change
    on_failure: always
