language: node_js
node_js:
- '8'
sudo: false
branches:
  only:
  - master
os:
- linux
install:
- npm install
- npm run build
script:
- npm test --silent
deploy:
  - provider: npm
    email: dev@xcomponent.com
    api_key:
      secure: EO9OP5OMhrER1hV9kcfz5SM+b1l/NXOo18EfxLaCxK2tQ4rDMODkhonyaO/ULxvPgOD1F1dHYKLGnjC03Xhxyh+aHUG/nl5AoxL9zMiieVy4TXI+Lu3jnRBnCnFJfKKRyB4fd8jjHYVxdI4NQV97jrWQ+aXiSo5fJFZe0A27iKXUoKeqo+T3pTvKzFPzqj0Lsr4g7KRw0FBuEnxq6ZTtcREWSxz6UUjw8u+CnDkGFb3Ol4U9RQO1DFPVQl0eAnLeTdfcVeHy6HYu6NTqQpmDhetj8L6QfO5w/FMFUr4YindLN012748u79IYzvb400HrhyZQd5RRc8WklT0kJ2hFtvbBtO5h698PG+x+GA0Tlkls194nH6Ogm8OyKQx9J+MUNUfpSFYpABfbrp+JMAXTGrU1+PhvLy5RT3vPufqgTypG4P0R73DC2UP4n0/38uqVVVyu6TB7b2KIUWfPFFcEW4eaTZJnN7EDnI3FVfIesgvHrgw+LZ7bT+LRwm1F7b2tdCCNTABtR9QlLsGjLoPXseBIpBfEwxh4j5OlUldgreJKR/mGULdq2ZEbyDK864d1GgDhjrtC4AiN0B0KKAt6xQdaN3NAGIuqiF+rZ3PScRHUePca1qBXDQHw0fcM4TrynYHqmMMm9yDigDqXb9ojXofXnhta94aowzxrAURoJn0=
    on:
      branch: master
      condition: "`./checkTag.sh` = RELEASE"
  - provider: npm
    email: dev@xcomponent.com
    tag: next001
    api_key:
      secure: EO9OP5OMhrER1hV9kcfz5SM+b1l/NXOo18EfxLaCxK2tQ4rDMODkhonyaO/ULxvPgOD1F1dHYKLGnjC03Xhxyh+aHUG/nl5AoxL9zMiieVy4TXI+Lu3jnRBnCnFJfKKRyB4fd8jjHYVxdI4NQV97jrWQ+aXiSo5fJFZe0A27iKXUoKeqo+T3pTvKzFPzqj0Lsr4g7KRw0FBuEnxq6ZTtcREWSxz6UUjw8u+CnDkGFb3Ol4U9RQO1DFPVQl0eAnLeTdfcVeHy6HYu6NTqQpmDhetj8L6QfO5w/FMFUr4YindLN012748u79IYzvb400HrhyZQd5RRc8WklT0kJ2hFtvbBtO5h698PG+x+GA0Tlkls194nH6Ogm8OyKQx9J+MUNUfpSFYpABfbrp+JMAXTGrU1+PhvLy5RT3vPufqgTypG4P0R73DC2UP4n0/38uqVVVyu6TB7b2KIUWfPFFcEW4eaTZJnN7EDnI3FVfIesgvHrgw+LZ7bT+LRwm1F7b2tdCCNTABtR9QlLsGjLoPXseBIpBfEwxh4j5OlUldgreJKR/mGULdq2ZEbyDK864d1GgDhjrtC4AiN0B0KKAt6xQdaN3NAGIuqiF+rZ3PScRHUePca1qBXDQHw0fcM4TrynYHqmMMm9yDigDqXb9ojXofXnhta94aowzxrAURoJn0=
    on:
      branch: master
      condition: "`./checkTag.sh` = BETA"
notifications:
  slack:
    secure: hKTMOBgJ0iX6UKEPFPgoch1Z9UQ4JZZnJZSu7BCIyncvrOaUcotpfhYl94gtbWRRjvOqzxF9tGoTOQzTKR78BsotvavjGU3eV6+3jIMWu8Ld4WMInoo7hfNbzJ5RyPEnLlh4+lK5Gs4PjRElRtglo3I2k0dU7bfcZE1EgSANW1+qbCmuZneDnpTsQYq0KJE7Ql1LL4vd8nj1rQa2cy0E3Vi3Tz38wrmQDpMMlcMfzMX4BNlR+Ru7hcpp7py6n6Sg9TxXdN5nEPATkrc1fFNMBtdHuNY06g2BhzHdZdcz9TWOmuQhi5A2/4rjpbT+w4owSw3OBj0C0moG7v02FtAz2P021T9I+rL6XW9maw8jRXaSAO64/BuZ2MuDRqftQuv7bBIR+MN2eI5e9gNzyAR7QkYitIumHocGQdK6Fv6ztKcLKq19ErttNJ+kb2oNu8h7VOXahm7ZX9g8bkaMUJ18Vl03lwvJACYBXDh/zBpqp96GUSZPl1sa3JVjA1ehGIjdlUuV7Q6GKZnmEv537KhnONpaRvERi/MbuhJN0YrFiLbw7hiTO+wsNk4h6o6rALX79MV/dDk1SQOCZ0OwQtRyXGlrzCkAPzDHIgBbtGDjGnlOu9zpzaiBN7H6BO4ZfGyZJaa+CV5ljpRgHHiVC0zohz+x1SzeM+0lkh61Kb69BrM=
    on_success: change
    on_failure: always
