language: node_js
node_js:
- '8'
sudo: false
branches:
  only:
  - master
os:
- linux
install:
- npm install
- npm run build
script:
- npm test --silent
notifications:
  slack:
    secure: hKTMOBgJ0iX6UKEPFPgoch1Z9UQ4JZZnJZSu7BCIyncvrOaUcotpfhYl94gtbWRRjvOqzxF9tGoTOQzTKR78BsotvavjGU3eV6+3jIMWu8Ld4WMInoo7hfNbzJ5RyPEnLlh4+lK5Gs4PjRElRtglo3I2k0dU7bfcZE1EgSANW1+qbCmuZneDnpTsQYq0KJE7Ql1LL4vd8nj1rQa2cy0E3Vi3Tz38wrmQDpMMlcMfzMX4BNlR+Ru7hcpp7py6n6Sg9TxXdN5nEPATkrc1fFNMBtdHuNY06g2BhzHdZdcz9TWOmuQhi5A2/4rjpbT+w4owSw3OBj0C0moG7v02FtAz2P021T9I+rL6XW9maw8jRXaSAO64/BuZ2MuDRqftQuv7bBIR+MN2eI5e9gNzyAR7QkYitIumHocGQdK6Fv6ztKcLKq19ErttNJ+kb2oNu8h7VOXahm7ZX9g8bkaMUJ18Vl03lwvJACYBXDh/zBpqp96GUSZPl1sa3JVjA1ehGIjdlUuV7Q6GKZnmEv537KhnONpaRvERi/MbuhJN0YrFiLbw7hiTO+wsNk4h6o6rALX79MV/dDk1SQOCZ0OwQtRyXGlrzCkAPzDHIgBbtGDjGnlOu9zpzaiBN7H6BO4ZfGyZJaa+CV5ljpRgHHiVC0zohz+x1SzeM+0lkh61Kb69BrM=
    on_success: change
    on_failure: always
