language: node_js
node_js:
- '8'
- '10'
sudo: false
os:
- linux
cache:
  directories:
  - node_modules
install:
- yarn install
script:
- yarn run lint
- yarn run test --coverage
- yarn build
deploy:
  - provider: npm
    email: dev@xcomponent.com
    skip_cleanup: true
    api_key:
      secure: ULR/HFjPUO1gUZ/B8Lei57vKdOU7TVLUwjFf32XwbmnSzBzVbZ7NufPqOPvDQyKtSS8t/DcBMfbx3pXV4fMADSeMIjCwPditstIWLbLgVr+/CFsaEwOVcZX27ev9KBeLEkSy0yntBUnE4vnp9K5139aAUms9a2iEc3EsU6/tlSPnvEY60lEJYZqg4a9Uh+HDvk9+NNLczR43Q0laj9S3akAoVGcvthuJX4XsS4QrO1UG1i9T7BKBB/vG+fP2CNQaY1t/OcopPs8sFFzycIoRZsS+Cphf4ILGxIenAz+iAuE6bKpvgWlptqewJmQVlVidT183htVXnEfRkJ9/SloyV/1+vJNEDB6U8QbuE2o67hEiV7/TbYA18t07dLzmnHBfPYCfZc/Wt4j5Ics441TRT2P5FOMUm2j5mrnXDvfhuQuDbq/JycoOjQuZDo1lji+++3RC+GbcZfWyVrdMcBNu+J76zazpjlop84J7rHj/jLd9ol7Zw/CawaPFa6yoAgzIu8lj2BTZ335jrdvcdrukA4sZ10NAg6JcXolv09uk7rOr84AdduL+04K4Bgh7poFDmIQtKswrM0IvQomiWESpAzQ6sw2mo6yFZs8U7tBrFy/QwAZgB8wX5d3WQT1lNN85kGU2RLUiNAaDtM7UeMW+Ie8XliGKh3zSQb8/5ZKtmmE=
    on:
      tags: true
      node : '10'
      condition: "`./checkTag.sh` = RELEASE"
  - provider: npm
    email: dev@xcomponent.com
    skip_cleanup: true
    tag: next
    api_key:
      secure: ULR/HFjPUO1gUZ/B8Lei57vKdOU7TVLUwjFf32XwbmnSzBzVbZ7NufPqOPvDQyKtSS8t/DcBMfbx3pXV4fMADSeMIjCwPditstIWLbLgVr+/CFsaEwOVcZX27ev9KBeLEkSy0yntBUnE4vnp9K5139aAUms9a2iEc3EsU6/tlSPnvEY60lEJYZqg4a9Uh+HDvk9+NNLczR43Q0laj9S3akAoVGcvthuJX4XsS4QrO1UG1i9T7BKBB/vG+fP2CNQaY1t/OcopPs8sFFzycIoRZsS+Cphf4ILGxIenAz+iAuE6bKpvgWlptqewJmQVlVidT183htVXnEfRkJ9/SloyV/1+vJNEDB6U8QbuE2o67hEiV7/TbYA18t07dLzmnHBfPYCfZc/Wt4j5Ics441TRT2P5FOMUm2j5mrnXDvfhuQuDbq/JycoOjQuZDo1lji+++3RC+GbcZfWyVrdMcBNu+J76zazpjlop84J7rHj/jLd9ol7Zw/CawaPFa6yoAgzIu8lj2BTZ335jrdvcdrukA4sZ10NAg6JcXolv09uk7rOr84AdduL+04K4Bgh7poFDmIQtKswrM0IvQomiWESpAzQ6sw2mo6yFZs8U7tBrFy/QwAZgB8wX5d3WQT1lNN85kGU2RLUiNAaDtM7UeMW+Ie8XliGKh3zSQb8/5ZKtmmE=
    on:
      tags: true
      node : '10'
      condition: "`./checkTag.sh` = BETA"
notifications:
  slack:
    secure: hKTMOBgJ0iX6UKEPFPgoch1Z9UQ4JZZnJZSu7BCIyncvrOaUcotpfhYl94gtbWRRjvOqzxF9tGoTOQzTKR78BsotvavjGU3eV6+3jIMWu8Ld4WMInoo7hfNbzJ5RyPEnLlh4+lK5Gs4PjRElRtglo3I2k0dU7bfcZE1EgSANW1+qbCmuZneDnpTsQYq0KJE7Ql1LL4vd8nj1rQa2cy0E3Vi3Tz38wrmQDpMMlcMfzMX4BNlR+Ru7hcpp7py6n6Sg9TxXdN5nEPATkrc1fFNMBtdHuNY06g2BhzHdZdcz9TWOmuQhi5A2/4rjpbT+w4owSw3OBj0C0moG7v02FtAz2P021T9I+rL6XW9maw8jRXaSAO64/BuZ2MuDRqftQuv7bBIR+MN2eI5e9gNzyAR7QkYitIumHocGQdK6Fv6ztKcLKq19ErttNJ+kb2oNu8h7VOXahm7ZX9g8bkaMUJ18Vl03lwvJACYBXDh/zBpqp96GUSZPl1sa3JVjA1ehGIjdlUuV7Q6GKZnmEv537KhnONpaRvERi/MbuhJN0YrFiLbw7hiTO+wsNk4h6o6rALX79MV/dDk1SQOCZ0OwQtRyXGlrzCkAPzDHIgBbtGDjGnlOu9zpzaiBN7H6BO4ZfGyZJaa+CV5ljpRgHHiVC0zohz+x1SzeM+0lkh61Kb69BrM=
    on_success: change
    on_failure: always
