language: node_js
node_js:
- '8'
- '10'
sudo: false
os:
- linux
cache:
  directories:
  - node_modules
install:
- yarn install
script:
- yarn run lint
- yarn run test --coverage
- yarn build
deploy:
  - provider: npm
    email: dev@xcomponent.com
    skip_cleanup: true
    api_key:
      secure: ItolgEW9AuXawyfDPX9VifuRzdrNGAqqw68COeJczpqXIldIIK3o5PboY6HbPkK9xySHVxp2X4qe1jui/TLcPAo9Eu0c04dYdORmqCyrLctQOGX9RggKnpHRa7ws0224efZZQnV0YPpPAzPFqK17g54y3RKdrWqvO1NHlP9diW+25rCOyraMMuDY/3ShxiZ0i5j0tU752m5hTIbYIYxWH+Tewp8HEKiU8N+AWhTPiRF/LP1geqkMkesYj6jaRdTFRavfiqnQHEdMC6rY02xyyzsQHBNIp4HSrsY9RsjONNYbBvOJUUjEE821r76XLDSQTlV8lqnBWGBJ8SsPWXwcmqYW3k4GeDzebjY5YLyglfzHVkhoLGOH1WMvLcJdSuMTA6MXV/RYjRmAFnB1AOba97mNmjGrJvPuzo4PEsbq9VbwHtI1R3wiHm50pOiXsR1OPX3VRg5X/vAkPDjYtCZzyELHDzF0jwu85NrLk1szVHEJQKAB3f6WWJeF1/xLAbleNyEueXYM1eNddUkgHl2wUUbNBzIQhV+KLBjTW3Or+1ob8l9uGC8wh+QWMFNUvdH6EAaWqjwEsIrhm0bjxFeMr7OQT8Nz8J19f9Xr5Zw1qI02qH5Qt7NyFfIH1lS3lRgMa2LfOkwVPc8m3tnbv8Z821cB/QFHzs5nbYpBYxFthZg=
    on:
      branch: master
      node : '10'
      condition: "`./checkTag.sh` = RELEASE"
  - provider: npm
    email: dev@xcomponent.com
    skip_cleanup: true
    tag: next
    api_key:
      secure: ItolgEW9AuXawyfDPX9VifuRzdrNGAqqw68COeJczpqXIldIIK3o5PboY6HbPkK9xySHVxp2X4qe1jui/TLcPAo9Eu0c04dYdORmqCyrLctQOGX9RggKnpHRa7ws0224efZZQnV0YPpPAzPFqK17g54y3RKdrWqvO1NHlP9diW+25rCOyraMMuDY/3ShxiZ0i5j0tU752m5hTIbYIYxWH+Tewp8HEKiU8N+AWhTPiRF/LP1geqkMkesYj6jaRdTFRavfiqnQHEdMC6rY02xyyzsQHBNIp4HSrsY9RsjONNYbBvOJUUjEE821r76XLDSQTlV8lqnBWGBJ8SsPWXwcmqYW3k4GeDzebjY5YLyglfzHVkhoLGOH1WMvLcJdSuMTA6MXV/RYjRmAFnB1AOba97mNmjGrJvPuzo4PEsbq9VbwHtI1R3wiHm50pOiXsR1OPX3VRg5X/vAkPDjYtCZzyELHDzF0jwu85NrLk1szVHEJQKAB3f6WWJeF1/xLAbleNyEueXYM1eNddUkgHl2wUUbNBzIQhV+KLBjTW3Or+1ob8l9uGC8wh+QWMFNUvdH6EAaWqjwEsIrhm0bjxFeMr7OQT8Nz8J19f9Xr5Zw1qI02qH5Qt7NyFfIH1lS3lRgMa2LfOkwVPc8m3tnbv8Z821cB/QFHzs5nbYpBYxFthZg=
    on:
      branch: master
      node : '10'
      condition: "`./checkTag.sh` = BETA"
notifications:
  slack:
    secure: hKTMOBgJ0iX6UKEPFPgoch1Z9UQ4JZZnJZSu7BCIyncvrOaUcotpfhYl94gtbWRRjvOqzxF9tGoTOQzTKR78BsotvavjGU3eV6+3jIMWu8Ld4WMInoo7hfNbzJ5RyPEnLlh4+lK5Gs4PjRElRtglo3I2k0dU7bfcZE1EgSANW1+qbCmuZneDnpTsQYq0KJE7Ql1LL4vd8nj1rQa2cy0E3Vi3Tz38wrmQDpMMlcMfzMX4BNlR+Ru7hcpp7py6n6Sg9TxXdN5nEPATkrc1fFNMBtdHuNY06g2BhzHdZdcz9TWOmuQhi5A2/4rjpbT+w4owSw3OBj0C0moG7v02FtAz2P021T9I+rL6XW9maw8jRXaSAO64/BuZ2MuDRqftQuv7bBIR+MN2eI5e9gNzyAR7QkYitIumHocGQdK6Fv6ztKcLKq19ErttNJ+kb2oNu8h7VOXahm7ZX9g8bkaMUJ18Vl03lwvJACYBXDh/zBpqp96GUSZPl1sa3JVjA1ehGIjdlUuV7Q6GKZnmEv537KhnONpaRvERi/MbuhJN0YrFiLbw7hiTO+wsNk4h6o6rALX79MV/dDk1SQOCZ0OwQtRyXGlrzCkAPzDHIgBbtGDjGnlOu9zpzaiBN7H6BO4ZfGyZJaa+CV5ljpRgHHiVC0zohz+x1SzeM+0lkh61Kb69BrM=
    on_success: change
    on_failure: always
